### ISSUE TITLE
solid-start project can't access `import.meta.env`

### ISSUE THREAD

**Issue by greg-hammond** [nksaraf/vinxi#269]
Attempting to access `import.meta.env` gives a type error:    Property 'env' does not exist on type 'ImportMeta'

Per Nikhil this is an issue separate from what was fixed in #265.  There is an additional fix needed related to type exports within vinxi.

Steps to repro:
`pnpm create solid`
`pnpm install`

attempt to access import.meta.env within `app.tsx`

**Comment by edivados** [comment]
@nksaraf Any reason not to use `vinxi/types/client` instead of `vinxi/client` for now? The latter is empty and the reason it works with npm in solid-start seems to be because [Ryan added vite/client to tsconfig](https://github.com/solidjs/solid-start/commit/090df26bed0f91cd17fe1c206dd5469aeb315a11).

**Comment by Brendonovich** [comment]
Turns out the [Vinxi docs](https://vinxi.vercel.app/guide/aliases.html) and a lot of the examples use `vinxi/types/client` instead of `vinxi/client`. SS should probably be updated so that manually adding `vite/client` isn't necessary.
<img width="726" alt="image" src="https://github.com/nksaraf/vinxi/assets/14191578/2e10c4a6-90cc-4530-9403-05015bd98906">

**Comment by edivados** [comment]
Yeah. SolidStart examples have been updated some time ago to use `vinxi/types/client` so this should not be a problem anymore.

**Comment by greg-hammond** [comment]
I'm fine to close this - it seems that usage of `vinxi/types/client` has percolated through the ecosystem, and this is no longer an issue.
