### ISSUE TITLE
[Bug?]: @vanilla-extract/vite-plugin causes errors in console during build's transform solidjs/solid-start#1224

### ISSUE THREAD

**Issue by nksaraf** [nksaraf/vinxi#98]

**Comment by Nvos** [comment]
# Reproduction

https://github.com/Nvos/vanilla-extract-vinxi-repro

Pretty much solid start scaffold with added vanilla extract vite plugin, just do `pnpm dev` and navigate to app via URL

# Notes
- Error happens when importing vanilla extract files `*.css.ts`
- Took look at vanilla extract and it seems that error happens for relative path files, during dev it seems that there's both relative and absolute path file being resolved and relative one fails due to vanilla extract cache containing absolute path key
- Happens only during dev after navigation to page containing vanilla-extract import
- Seems to be working on production build

**Comment by nksaraf** [comment]
I am trying to run this and its working fine without errors. Do i need to add any files or make any changes to see this error? Can you put in a screen recording with the error so i can see how to reproduce it. Can you also try running this with latest vinxi 0.3.8 and see if its fine or not.

**Comment by Nvos** [comment]
Seems that issue is present on latest version of vinxi as well, thought checked out if it happens on linux and it seems to work on it. So it seems to be relevant to windows only which seems likely as it seems to be related to file paths

**Comment by nksaraf** [comment]
ahh okay windows issue.. maybe we can add a test on windows for this or somebody can try to debug this on windows ( i usually don't have access to a windows system)

**Comment by Nvos** [comment]
After some debugging issue seems to be related to `vanilla-extract` in code related to absolute path resolution, opened issue on their repo https://github.com/vanilla-extract-css/vanilla-extract/issues/1344

**Comment by nksaraf** [comment]
Ahh great okay makes sense. I'll close this for now then. If anything goes wrong agin feel free to open this
